language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - jruby-head

before_install:
  - gem update bundler

bundler_args: --without guard

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
  fast_finish: true

notifications:
  email: pauly@buzbox.net
